import requests
from bs4 import BeautifulSoup
import csv
from tqdm import tqdm
from datetime import datetime
import time

# ScraperAPI Key
SCRAPER_API_KEY = "aa8451bdbcae28cdb954d2bfb238435d"

# Function to standardize the publication date
def format_date(date_str):
    try:
        formatted_date = datetime.strptime(date_str, "%B %d, %Y").strftime("%Y-%m-%d")
        return formatted_date
    except ValueError:
        return date_str  # Return original if formatting fails

# Function to scrape details from an article using ScraperAPI
def scrape_article(article_url):
    try:
        # Fetch the webpage content using ScraperAPI
        payload = {
            "api_key": SCRAPER_API_KEY,
            "url": article_url,
            "render": "true"  # Enable JavaScript rendering
        }
        response = requests.get("https://api.scraperapi.com/", params=payload)

        # Check if response is successful
        if response.status_code != 200:
            print(f"Failed to fetch {article_url}, Status Code: {response.status_code}")
            return None

        soup = BeautifulSoup(response.text, "html.parser")

        # Extract Metadata and Article Content
        title = soup.find("h1").get_text(strip=True) if soup.find("h1") else "N/A"
        meta_description = soup.find("meta", attrs={"name": "description"})
        meta_keywords = soup.find("meta", attrs={"name": "keywords"})
        canonical_url = soup.find("link", rel="canonical")

        date_tag = soup.find("time")
        publication_date = format_date(date_tag.get("datetime", date_tag.text.strip())) if date_tag else "N/A"

        content_div = soup.find("div", class_="nmss-body-block")
        full_text = "\n".join([span.get_text(strip=True) for span in content_div.find_all("span")]) if content_div else "N/A"

        return {
            "Title": title,
            "Meta Description": meta_description["content"] if meta_description else "N/A",
            "Meta Keywords": meta_keywords["content"] if meta_keywords else "N/A",
            "Canonical URL": canonical_url["href"] if canonical_url else "N/A",
            "Publication Date": publication_date,
            "Full Article Text": full_text,
            "Article Link": article_url
        }
    except Exception as e:
        print(f"Error scraping {article_url}: {e}")
        return None

# CSV file to store the extracted data
csv_file = "scraped_articles_scraperapi.csv"
with open(csv_file, "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["Title", "Meta Description", "Meta Keywords", "Canonical URL", "Publication Date", "Full Article Text", "Article Link"])

# List of URLs to scrape
urls = [
    "https://www.nationalmssociety.org/news-and-magazine/news/depression-anxiety-pregnancy",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-warning-anaphylaxis-ga",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-welcomes-leadership-team-members",
    "https://www.nationalmssociety.org/news-and-magazine/news/federal-trade-commission-releases-new-report",
    "https://www.nationalmssociety.org/news-and-magazine/news/dmts-pregnancy",
    "https://www.nationalmssociety.org/news-and-magazine/news/associations-with-menopause",
    "https://www.nationalmssociety.org/news-and-magazine/news/dept-of-transportation-enacts-protections",
    "https://www.nationalmssociety.org/news-and-magazine/news/congress-continues-work-on-spending-bill",
    "https://www.nationalmssociety.org/news-and-magazine/news/summer-ms-research-program",
    "https://www.nationalmssociety.org/news-and-magazine/news/tolebrutinib-breakthrough-therapy",
    "https://www.nationalmssociety.org/news-and-magazine/news/pain-medications-and-prodrome",
    "https://www.nationalmssociety.org/news-and-magazine/news/department-of-veterans-affairs-telehealth",
    "https://www.nationalmssociety.org/news-and-magazine/news/social-drivers-mri-outcomes-in-poms",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-partners-with-nrha",
    "https://www.nationalmssociety.org/news-and-magazine/news/myelin-repair-and-neuronal-death",
    "https://www.nationalmssociety.org/news-and-magazine/news/understanding-autoimmunity-grants",
    "https://www.nationalmssociety.org/news-and-magazine/news/rising-cost-medications",
    "https://www.nationalmssociety.org/news-and-magazine/news/cbt-medication-fatigue",
    "https://www.nationalmssociety.org/news-and-magazine/news/gene-editing-myelin-repair",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-and-cancer-risk",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-commits-over-4-million-for-restore",
    "https://www.nationalmssociety.org/news-and-magazine/news/ca-medical-debt-legislative-win",
    "https://www.nationalmssociety.org/news-and-magazine/news/phase-3-clinical-trials-of-evobrutinib",
    "https://www.nationalmssociety.org/news-and-magazine/news/congress-passes-short-term-2025-funding",
    "https://www.nationalmssociety.org/news-and-magazine/news/cholesterol-lowering-simvastatin",
    "https://www.nationalmssociety.org/news-and-magazine/news/2024-horne-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-approves-ocrevus-zunovo",
    "https://www.nationalmssociety.org/news-and-magazine/news/registration-ectrims-day",
    "https://www.nationalmssociety.org/news-and-magazine/news/leptin-intermittent-calorie-restriction",
    "https://www.nationalmssociety.org/news-and-magazine/news/results-tolebrutinib-announce",
    "https://www.nationalmssociety.org/news-and-magazine/news/refined-pathways-to-cures-roadmap-published",
    "https://www.nationalmssociety.org/news-and-magazine/news/brain-cells-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-and-risk-of-alzheimers",
    "https://www.nationalmssociety.org/news-and-magazine/news/adstep-physical-therapy-program",
    "https://www.nationalmssociety.org/news-and-magazine/news/covid-vaccine-safety",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-weight-loss-drugs",
    "https://www.nationalmssociety.org/news-and-magazine/news/bowel-control-probiotics",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-study-alert-sprint-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/mindfulness-program-study",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-society-president-and-ceo",
    "https://www.nationalmssociety.org/news-and-magazine/news/asian-people-with-ms-singapore-study",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-jersey-general-assembly-passes-med",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-president-and-ceo-retires",
    "https://www.nationalmssociety.org/news-and-magazine/news/investigators-recruiting-hispanics-latinx",
    "https://www.nationalmssociety.org/news-and-magazine/news/recruiting-nationwide-study-ahsct",
    "https://www.nationalmssociety.org/news-and-magazine/news/possible-marker-progression",
    "https://www.nationalmssociety.org/news-and-magazine/news/consortium-of-ms-centers-meeting-2024",
    "https://www.nationalmssociety.org/news-and-magazine/news/minnesota-governor-signs-debt-fairness-act",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-connecticut-law-makes-healthcare-access",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-sponsors-bike-ms-2024",
    "https://www.nationalmssociety.org/news-and-magazine/news/commercial-research-new-studies-repair",
    "https://www.nationalmssociety.org/news-and-magazine/news/stem-cell-trial-results-published",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-and-va-expand-care",
    "https://www.nationalmssociety.org/news-and-magazine/news/workshop-aging-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/small-study-cycling",
    "https://www.nationalmssociety.org/news-and-magazine/news/faa-reauthorized-accessible-air-travel",
    "https://www.nationalmssociety.org/news-and-magazine/news/novel-compound-myelin-repair-mice",
    "https://www.nationalmssociety.org/news-and-magazine/news/hhs-disability-discrimination-ruling",
    "https://www.nationalmssociety.org/news-and-magazine/news/pathways-to-ms-cures-advances-reported",
    "https://www.nationalmssociety.org/news-and-magazine/news/researchers-uncover-immune-signature",
    "https://www.nationalmssociety.org/news-and-magazine/news/muscle-tightness-affects-people-with-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/abnormalities-in-cervix-and-dmts",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-commits-over-16-million-for-research",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activist-testifies-on-telehealth",
    "https://www.nationalmssociety.org/news-and-magazine/news/highly-effective-therapies-children",
    "https://www.nationalmssociety.org/news-and-magazine/news/dr-rhonda-voskuhl-wins-2024-dystel-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-sponsors-of-walk-ms-2024",
    "https://www.nationalmssociety.org/news-and-magazine/news/35-patient-organizations-celebrate-rule",
    "https://www.nationalmssociety.org/news-and-magazine/news/covid-19-and-ms-get-the-facts",
    "https://www.nationalmssociety.org/news-and-magazine/news/researchers-compare-outcomes-50-and-over",
    "https://www.nationalmssociety.org/news-and-magazine/news/investigators-recruiting-phase-2-trial",
    "https://www.nationalmssociety.org/news-and-magazine/news/congress-approves-fy24-funding",
    "https://www.nationalmssociety.org/news-and-magazine/news/researchers-unearth-clues-to-ms-development",
    "https://www.nationalmssociety.org/news-and-magazine/news/actrims-forum-showcases-advancements",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-delays-approval-of-ga-depot-injection",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-applauds-air-travel-accessibility",
    "https://www.nationalmssociety.org/news-and-magazine/news/global-surveys-improve-health-for-women",
    "https://www.nationalmssociety.org/news-and-magazine/news/statement-from-national-ms-society",
    "https://www.nationalmssociety.org/news-and-magazine/news/physical-function-black-and-white-people",
    "https://www.nationalmssociety.org/news-and-magazine/news/a-statement-from-the-national-ms-society",
    "https://www.nationalmssociety.org/news-and-magazine/news/clinical-trials-in-progressive-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/black-americans-genetics-studies",
    "https://www.nationalmssociety.org/news-and-magazine/news/barancik-prize-sergio-baranzini",
    "https://www.nationalmssociety.org/news-and-magazine/news/disparities-in-pregnancy-experiences",
    "https://www.nationalmssociety.org/news-and-magazine/news/remote-coaching-reduce-stress-depression",
    "https://www.nationalmssociety.org/news-and-magazine/news/cell-communication-hotspots-in-zebrafi",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-brought-to-europe-5000-years-ago",
    "https://www.nationalmssociety.org/news-and-magazine/news/inflation-reduction-act-catastrophic-coverage",
    "https://www.nationalmssociety.org/news-and-magazine/news/can-brain-stimulation-improve-cognition",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-alliance-announces-new-funding",
    "https://www.nationalmssociety.org/news-and-magazine/news/positive-results-from-mouse-studies-test",
    "https://www.nationalmssociety.org/news-and-magazine/news/2023-impact",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-commits-over-4-million",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-approves-portable-nerve-stimulator",
    "https://www.nationalmssociety.org/news-and-magazine/news/early-stem-cell-trial-shows-safety-spms",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-responds-to-proposed-rule",
    "https://www.nationalmssociety.org/news-and-magazine/news/experimental-therapy-targets-cells-with-ebv",
    "https://www.nationalmssociety.org/news-and-magazine/news/survey-creating-patient-centered-healthcare",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-evidence-biomarkers-predict-ms-outcomes",
    "https://www.nationalmssociety.org/news-and-magazine/news/researchers-report-possible-ms-trigger",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-cooling-garments-restore-function",
    "https://www.nationalmssociety.org/news-and-magazine/news/msmilan23-highlights-global-efforts",
    "https://www.nationalmssociety.org/news-and-magazine/news/drug-pricing-law-made-permanent-in-california",
    "https://www.nationalmssociety.org/news-and-magazine/news/congress-passes-short-term-funding-bill-2023",
    "https://www.nationalmssociety.org/news-and-magazine/news/the-biden-administration-marks-progress",
    "https://www.nationalmssociety.org/news-and-magazine/news/sleep-genes-linked-to-risk-of-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/online-program-reduces-depression",
    "https://www.nationalmssociety.org/news-and-magazine/news/psychiatric-conditions-may-provide-hints",
    "https://www.nationalmssociety.org/news-and-magazine/news/exercise-cognitive-rehab-thinking-speed",
    "https://www.nationalmssociety.org/news-and-magazine/news/ucla-neurologist-wins-rachel-horne-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/survey-better-way-to-describe-ms-stages",
    "https://www.nationalmssociety.org/news-and-magazine/news/what-inflation-reduction-act-means-for-you",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-brain-bank-needs-you",
    "https://www.nationalmssociety.org/news-and-magazine/news/asian-americans-and-ms-new-study",
    "https://www.nationalmssociety.org/news-and-magazine/news/health-research-priorities-for-women-with-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-applauds-cms-drug-announcement",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-approves-tyruko-for-relapsing-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-treatment-extends-time-to-first-symptoms",
    "https://www.nationalmssociety.org/news-and-magazine/news/diet-quality-linked-to-less-disability",
    "https://www.nationalmssociety.org/news-and-magazine/news/papers-published-on-improving-ms-therapy",
    "https://www.nationalmssociety.org/news-and-magazine/news/researchers-engineer-a-probiotic",
    "https://www.nationalmssociety.org/news-and-magazine/news/dot-releases-rule-accessible-lavatories",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-coalition-applauds-who-decision",
    "https://www.nationalmssociety.org/news-and-magazine/news/us-house-of-reps-pass-faa-reauthorization",
    "https://www.nationalmssociety.org/news-and-magazine/news/is-it-ms-or-something-else-updated",
    "https://www.nationalmssociety.org/news-and-magazine/news/treatment-within-six-months-of-first-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-bills-pass-in-maine-ohio-and-texas",
    "https://www.nationalmssociety.org/news-and-magazine/news/early-novel-study-nerve-fibers",
    "https://www.nationalmssociety.org/news-and-magazine/news/clemastine-follow-up-imaging-study",
    "https://www.nationalmssociety.org/news-and-magazine/news/possible-genetic-basis-progressive-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-commits-over-19-million-research",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-older-adults-with-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/consortium-of-ms-centers-meeting",
    "https://www.nationalmssociety.org/news-and-magazine/news/multiple-sclerosis-organizations-commit",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-across-the-country",
    "https://www.nationalmssociety.org/news-and-magazine/news/president-biden-fiscal-responsibility",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-stress-disability-relapses",
    "https://www.nationalmssociety.org/news-and-magazine/news/global-summit-reviews",
    "https://www.nationalmssociety.org/news-and-magazine/news/ahsct-shows-effectiveness-when-compared",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-research-how-ebv-may-trigger-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/medicare-covers-seat-elevation",
    "https://www.nationalmssociety.org/news-and-magazine/news/comorbid-conditions-appear",
    "https://www.nationalmssociety.org/news-and-magazine/news/research-study-prevalence",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-return-to-in-person",
    "https://www.nationalmssociety.org/news-and-magazine/news/studies-on-ms-diets-stem-cells",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-trial-alert-thinking-speed",
    "https://www.nationalmssociety.org/news-and-magazine/news/news-on-mediterranean-diet-stem-cells",
    "https://www.nationalmssociety.org/news-and-magazine/news/reports-suggest-vitamin-d-not-reduce-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/first-generic-versions-of-aubagio",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-sponsors-bike-ms-2023",
    "https://www.nationalmssociety.org/news-and-magazine/news/dr-roland-martin-awarded-dystel-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/patient-and-provider-groups-warn",
    "https://www.nationalmssociety.org/news-and-magazine/news/sexual-function-satisfaction-may-be-low",
    "https://www.nationalmssociety.org/news-and-magazine/news/victory-in-north-carolina-medicaid",
    "https://www.nationalmssociety.org/news-and-magazine/news/us-reps-michael-burgess-and-lori-trahan",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-helps-increase-physical-activity",
    "https://www.nationalmssociety.org/news-and-magazine/news/no-relapse-increase-fertility-treatment",
    "https://www.nationalmssociety.org/news-and-magazine/news/pathways-research-highlighted-at-actrims",
    "https://www.nationalmssociety.org/news-and-magazine/news/medicare-benefit-expansion-seat-elevation-equipment",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-endorses-air-carrier-access-amendments-act",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-recognizes-walk-ms-sponsors",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-ppms-may-differ-from-other-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/ruth-ann-marrie-awarded-barancik-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/research-link-sleep-thinking-problems",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-shows-opioid-prescriptions-higher",
    "https://www.nationalmssociety.org/news-and-magazine/news/conference-on-improving-ms-therapy",
    "https://www.nationalmssociety.org/news-and-magazine/news/investigators-stem-cell-injection-safe",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-commits-drive-pathways-to-cures",
    "https://www.nationalmssociety.org/news-and-magazine/news/less-physical-activity-worsening-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-trial-alert-seeking-people-relapsing",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-trial-alert-seeking-people-newly-diagnosed",
    "https://www.nationalmssociety.org/news-and-magazine/news/congress-passes-omnibus-bill",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-on-disclosure-decisions",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-active-spms-may-benefit-from-ahsct",
    "https://www.nationalmssociety.org/news-and-magazine/news/what-triggers-changes-in-gut-bacteria",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-treatment-extends-time-to-symptoms",
    "https://www.nationalmssociety.org/news-and-magazine/news/respect-for-marriage-act-what-it-means",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-york-passes-legislation-to-protect-p",
    "https://www.nationalmssociety.org/news-and-magazine/news/researchers-share-pathways-progress",
    "https://www.nationalmssociety.org/news-and-magazine/news/patient-groups-urge-u-s-district-court",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-efforts-to-speed-clinical-trials",
    "https://www.nationalmssociety.org/news-and-magazine/news/proposed-new-framework-to-describe-ms-types",
    "https://www.nationalmssociety.org/news-and-magazine/news/people-with-ms-take-five-or-more-meds",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-step-therapy-reform",
    "https://www.nationalmssociety.org/news-and-magazine/news/victory-for-ms-activists-in-pennsylvania",
    "https://www.nationalmssociety.org/news-and-magazine/news/biomarkers-diet-ppms-epstein-barr-ectrims",
    "https://www.nationalmssociety.org/news-and-magazine/news/progressive-ms-alliance-invest-therapies",
    "https://www.nationalmssociety.org/news-and-magazine/news/experts-provide-roadmap-to-research",
    "https://www.nationalmssociety.org/news-and-magazine/news/congress-passes-short-term-funding-bill",
    "https://www.nationalmssociety.org/news-and-magazine/news/chronic-itching-overlooked-in-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/gut-bacteria-linked-to-ms-susceptibility",
    "https://www.nationalmssociety.org/news-and-magazine/news/ppms-trial-fenebrutinib-ocrevus",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-phase-trial-experimental-fenebrutinib",
    "https://www.nationalmssociety.org/news-and-magazine/news/results-of-phase-ublituximab-trials-published",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-prevalence-tied-to-socioeconomic-factors",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-key-role-in-legislation",
    "https://www.nationalmssociety.org/news-and-magazine/news/drug-price-reform-in-inflation-reduction",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-society-invests-in-new-research",
    "https://www.nationalmssociety.org/news-and-magazine/news/intermittent-fasting-beneficial-changes",
    "https://www.nationalmssociety.org/news-and-magazine/news/weight-loss-surgery-affects-ms-course",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-suggest-rituximab-reduce-relapse-better",
    "https://www.nationalmssociety.org/news-and-magazine/news/research-priorities-earlier-detection",
    "https://www.nationalmssociety.org/news-and-magazine/news/dot-airline-passengers",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-approves-baclofen-oral-formulations",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-applauds-low-drug-cost-proposal",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-hbp-more-likely-in-black-people",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-places-hold-on-tolebrutinib-studies",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-centers-annual-focuses-on-pathways",
    "https://www.nationalmssociety.org/news-and-magazine/news/recruiting-study-covid-vaccine-booster",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-people-ms-improve-process-speed",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-pinpoints-four-novel-immune-culprits",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-make-their-voices-heard-at",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-celebrate-legislative-wins",
    "https://www.nationalmssociety.org/news-and-magazine/news/findings-show-reduced-cancer-screening",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-ms-as-common-in-black-people",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-confirms-high-costs-of-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/ppms-diet-emerging-therapies-at-aan",
    "https://www.nationalmssociety.org/news-and-magazine/news/prior-authorization-reform-legislation",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-georgia-legislative-victory",
    "https://www.nationalmssociety.org/news-and-magazine/news/maryland-general-assembly-passes-paid-le",
    "https://www.nationalmssociety.org/news-and-magazine/news/kathleen-jim-skinner-pathways-to-cures",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-recognizes-national-sponsors-of-bike-ms-2022",
    "https://www.nationalmssociety.org/news-and-magazine/news/experts-agree-on-pathways-to-ms-cures",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-recognizes-sponsors-walk-ms-returns",
    "https://www.nationalmssociety.org/news-and-magazine/news/barcelona-neurologist-wins-2022-dystel-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/smell-sensitive-predict-treatments-work",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-testifies-on-critica",
    "https://www.nationalmssociety.org/news-and-magazine/news/president-biden-signs-omnibus-bill-to-fu",
    "https://www.nationalmssociety.org/news-and-magazine/news/actrims-forum-focuses-on-ms-biomarkers",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-commits-to-health-equity-in-clinical",
    "https://www.nationalmssociety.org/news-and-magazine/news/novel-twins-study-pinpoints-immune-syste",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-suggests-online-meditation-pro",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-shows-blood-test-in-helping-predict-future-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/penn-med-neurologist-wins-barancik-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-joins-patient-advocacy-organizat",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-highlights-lack-of-diversity",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-endorses-stop-the-wait-act",
    "https://www.nationalmssociety.org/news-and-magazine/news/potential-mechanism-epstein-barr-virus",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-shows-evidence-role-of-epstein-barr",
    "https://www.nationalmssociety.org/news-and-magazine/news/reimbursing-at-home-covid-19-tests",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-federal-law-ends-most-unexpected-out",
    "https://www.nationalmssociety.org/news-and-magazine/news/socioeconomic-factors-linked-to-vision-a",
    "https://www.nationalmssociety.org/news-and-magazine/news/california-ms-activists-celebrate-wins",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-commits-nearly-7-million-for-ta",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-identifies-novel-subtype-of-cell-t",
    "https://www.nationalmssociety.org/news-and-magazine/news/progressive-ms-alliance-maps-research",
    "https://www.nationalmssociety.org/news-and-magazine/news/teriflunomide-study-in-kids-not-meet",
    "https://www.nationalmssociety.org/news-and-magazine/news/build-back-better-act-passes-house",
    "https://www.nationalmssociety.org/news-and-magazine/news/covid-19-vaccine-reactions",
    "https://www.nationalmssociety.org/news-and-magazine/news/consortium-of-ms-centers-annual",
    "https://www.nationalmssociety.org/news-and-magazine/news/international-mesenchymal-stem-cell-trial",
    "https://www.nationalmssociety.org/news-and-magazine/news/copays-count-coalition-applauds-help-copays-act",
    "https://www.nationalmssociety.org/news-and-magazine/news/myelin-repair-ppms-research-news-ectrims",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-cites-ahsct-as-viabl",
    "https://www.nationalmssociety.org/news-and-magazine/news/oral-malaria-drug-shows-benefit-in-study-ppms",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-covid-vaccines-immune-responses",
    "https://www.nationalmssociety.org/news-and-magazine/news/promising-path-for-future-treatment-ppms",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-invests-in-new-ms-research-workf",
    "https://www.nationalmssociety.org/news-and-magazine/news/people-with-ms-depression-increased-risk",
    "https://www.nationalmssociety.org/news-and-magazine/news/myelin-repair-strategy-for-ms-hits-snag",
    "https://www.nationalmssociety.org/news-and-magazine/news/survey-finds-gaps-in-some-types-of-insur",
    "https://www.nationalmssociety.org/news-and-magazine/news/recruiting-trial-ocrevus-placebo",
    "https://www.nationalmssociety.org/news-and-magazine/news/gene-variation-link-to-spms-black-people",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-authorizes-regen-cov-for-prevention",
    "https://www.nationalmssociety.org/news-and-magazine/news/emergency-preparedness-bills",
    "https://www.nationalmssociety.org/news-and-magazine/news/us-senate-passes-bipartisan-infrastructure",
    "https://www.nationalmssociety.org/news-and-magazine/news/two-diets-reduce-fatigue-improve-qol",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-society-funded-study-finds-that-high",
    "https://www.nationalmssociety.org/news-and-magazine/news/people-with-ms-not-at-greater-risk-for-g",
    "https://www.nationalmssociety.org/news-and-magazine/news/too-soon-to-make-recommendation-for-covi",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-celebrate-two-wins-in-conn",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-adds-to-growing-evidence-that",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-blood-biomarker-neurofilament-light",
    "https://www.nationalmssociety.org/news-and-magazine/news/patient-groups-praise-supreme-court-ruli",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-signs-on-to-statement",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-committed-to-dei",
    "https://www.nationalmssociety.org/news-and-magazine/news/several-wins-for-illinois-ms-activists-d",
    "https://www.nationalmssociety.org/news-and-magazine/news/virtual-ms-state-action-days",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-finds-healthy-diet-is-good-for-the-brain",
    "https://www.nationalmssociety.org/news-and-magazine/news/washington-ms-activists-expand-coverage",
    "https://www.nationalmssociety.org/news-and-magazine/news/mouse-study-by-society-funded-team-pinpo",
    "https://www.nationalmssociety.org/news-and-magazine/news/trial-recruiting-black-hispanic-latinx",
    "https://www.nationalmssociety.org/news-and-magazine/news/robotic-exoskeleton-improves-walking-thinking",
    "https://www.nationalmssociety.org/news-and-magazine/news/today-and-every-day-the-national-ms-soc",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-lifespan-women-with-ms-breast-cancer",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-strategy-for-myelin-repair-targeted",
    "https://www.nationalmssociety.org/news-and-magazine/news/thank-you-national-sponsors-of-bike-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/supported-team-uses-film-to-improve-unde",
    "https://www.nationalmssociety.org/news-and-magazine/news/virtual-aan-meeting-features-reports-on",
    "https://www.nationalmssociety.org/news-and-magazine/news/black-people-may-respond-differently-to-b-cell-therapy",
    "https://www.nationalmssociety.org/news-and-magazine/news/dystel-prize-professor-vojay-kuchroo",
    "https://www.nationalmssociety.org/news-and-magazine/news/people-with-ms-are-not-at-greater-risk-f",
    "https://www.nationalmssociety.org/news-and-magazine/news/georgia-pass-prior-authorization-reform",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-identifies-new-subtypes-of-ms-base",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-report-patients-pay-the-price-with",
    "https://www.nationalmssociety.org/news-and-magazine/news/clinical-trial-cell-therapy-in-progressive-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/moving-research-forward-ppms",
    "https://www.nationalmssociety.org/news-and-magazine/news/restless-leg-more-likely-with-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/veterans-spouses-caregivers-eligible",
    "https://www.nationalmssociety.org/news-and-magazine/news/published-results-from-covims-registry-h",
    "https://www.nationalmssociety.org/news-and-magazine/news/improving-balance-and-walking-rehab",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-approves-intramuscular-plegridy-rrms",
    "https://www.nationalmssociety.org/news-and-magazine/news/congress-passes-the-american-rescue-plan",
    "https://www.nationalmssociety.org/news-and-magazine/news/myelin-repair-and-lifestyle-diet-aging-at-actrims",
    "https://www.nationalmssociety.org/news-and-magazine/news/ms-activists-go-3-for-3-in-virginia",
    "https://www.nationalmssociety.org/news-and-magazine/news/society-evaluating-johnson-and-johnson-c",
    "https://www.nationalmssociety.org/news-and-magazine/news/jdrf-lupus-research-alliance-and-nation",
    "https://www.nationalmssociety.org/news-and-magazine/news/johns-hopkins-neuroscientist-wins-baranc",
    "https://www.nationalmssociety.org/news-and-magazine/news/u-s-representative-steve-chabot-announc",
    "https://www.nationalmssociety.org/news-and-magazine/news/improving-early-phase-clinical-trials",
    "https://www.nationalmssociety.org/news-and-magazine/news/estrogen-like-compound-repairs-myelin",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-study-most-pregnancy-complications",
    "https://www.nationalmssociety.org/news-and-magazine/news/researchers-discover-a-subset-of-brain-c",
    "https://www.nationalmssociety.org/news-and-magazine/news/fatty-acid-may-improve-immune-regulation",
    "https://www.nationalmssociety.org/news-and-magazine/news/president-biden-signs-executive-orders",
    "https://www.nationalmssociety.org/news-and-magazine/news/research-report-long-term-outcomes-ahsct",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-suggests-sunlight-reducing-ms-severity",
    "https://www.nationalmssociety.org/news-and-magazine/news/team-shows-neuroprotective-potential",
    "https://www.nationalmssociety.org/news-and-magazine/news/new-covid-related-studies-point-to-stres",
    "https://www.nationalmssociety.org/news-and-magazine/news/large-observational-study-confirms-long",
    "https://www.nationalmssociety.org/news-and-magazine/news/professor-alan-thompson-wins-sobek-prize",
    "https://www.nationalmssociety.org/news-and-magazine/news/study-suggests-no-increased-cancer-risks",
    "https://www.nationalmssociety.org/news-and-magazine/news/national-ms-society-releases-recommendations",
    "https://www.nationalmssociety.org/news-and-magazine/news/high-blood-pressure-common-in-ms",
    "https://www.nationalmssociety.org/news-and-magazine/news/expert-panel-outlines-biomarker-treatments",
    "https://www.nationalmssociety.org/news-and-magazine/news/comorbidities-linked-to-disease-activity",
    "https://www.nationalmssociety.org/news-and-magazine/news/exercise-and-physical-activity-recommend",
    "https://www.nationalmssociety.org/news-and-magazine/news/wellness-research-strategies-improving-diet",
    "https://www.nationalmssociety.org/news-and-magazine/news/hsct-shows-benefits-in-some-people-with",
    "https://www.nationalmssociety.org/news-and-magazine/news/young-ms-researchers-share-findings",
    "https://www.nationalmssociety.org/news-and-magazine/news/international-ms-genetics-consortium-genes",
    "https://www.nationalmssociety.org/news-and-magazine/news/university-of-california-scientist-wins",
    "https://www.nationalmssociety.org/news-and-magazine/news/cdc-to-study-multiple-sclerosis-in-launc",
    "https://www.nationalmssociety.org/news-and-magazine/news/fda-issues-safety-measures-mri-contrast-agent",
    "https://www.nationalmssociety.org/news-and-magazine/news/nih-researcher-receives-prestigious-bara"
]

for url in tqdm(urls, desc="Scraping Articles"):
    article_data = scrape_article(url)

    if article_data:
        with open(csv_file, "a", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            writer.writerow([
                article_data["Title"],
                article_data["Meta Description"],
                article_data["Meta Keywords"],
                article_data["Canonical URL"],
                article_data["Publication Date"],
                article_data["Full Article Text"],
                article_data["Article Link"]
            ])

    time.sleep(1)  # Delay to prevent server overload

print("Scraping complete. Data saved to CSV file.")
